Domain: athena..corp
Domain_split: "{{ Domain.split('.') }}"
NetBIOS: '{{ Domain_split[0] }}'
DN: "DC={{ Domain_split|join(',DC=') }}"
Group_OU: "OU=Groups,{{ DN }}"

Other_Users:
    - steve
    - john
    - ben
    - rex
    - cody
    - jane
    - emma
    - tammy
    - frank