windows:
    dc:
      hosts:
        dc01:
          ansible_host: INSERT-IP
    workstation:
      hosts:
        wkst01:
          ansible_host: INSERTIP
        wkst02:
          ansible_host: INSERTIP
        wkst03:
          ansible_host: INSERTIP
    vars:
        ansible_user: ansible
        ansible_password: Passw0rd!
        ansible_port: 5986
        ansible_connection: winrm
        ansible_winrm_transport: basic
        ansible_winrm_server_cert_validation: ignore
        ansible_winrm_operation_timeout_sec: 120
        ansible_winrm_read_timeout_sec: 130
        windows_gateway: INSERT
        windows_mask: INSERT
        ansible_become_password: Passw0rd!
        callbacks_enabled: profile_tasks